#ifndef LLM_REWRITER_APP_DEFAULTS_H
#define LLM_REWRITER_APP_DEFAULTS_H

#ifndef LLM_REWRITER_APP_ID
#define LLM_REWRITER_APP_ID "llm_rewriter"
#endif

#ifndef LLM_REWRITER_APP_NAME
#define LLM_REWRITER_APP_NAME "LLM Rewriter"
#endif

#ifndef LLM_REWRITER_DEFAULT_WIDTH
#define LLM_REWRITER_DEFAULT_WIDTH 900
#endif

#ifndef LLM_REWRITER_DEFAULT_HEIGHT
#define LLM_REWRITER_DEFAULT_HEIGHT 650
#endif

#endif
